require 'bundler/setup'
require 'rspec/core/rake_task'
import 'lib/tasks/helix_runtime.rake'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

# `rake build` is now a dependency of `rake spec`
task :spec => :build
task :default => :spec
