# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e78bd811035396051333232bc8dc6d9bea0c6d747c24c1f1b658da62bd0179b4edc521ae0ccef88e5ad2fe4d428828243d0bef9bd651d3b1fc0123f49c3830a

test:
  secret_key_base: b46d11cc9419ea53b7a5a2c34fb777d5a08e54e45ac85ed77bec6d2dc1f6bf516166616005a2c65e344324cf4edc4e51fef574498d246954e9b121398054b681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
